### PR TITLE
Do not show `Dialog`s before `Activity` content view is attached.

### LINKED ISSUE #1001: `ComposeView` and `IllegalStateException: You can consumeRestoredStateForKey only after super.onCreate of corresponding component`
Update: we've found other, simpler recipes. `AndroidView` is not in the chain, dialog windows always are. More deets in comment.

We have a family of crashes that pass through the following points. (I'll post a complete stack trace in a follow on comment.)

```
IllegalStateException: You can consumeRestoredStateForKey only after super.onCreate of corresponding component
  SavedStateRegistry.consumeRestoredStateForKey
  AndroidComposeView.setOnViewTreeOwnersAvailable
  LifecycleRegistry.moveToState
  LifecycleRegistry.setCurrentState
  RealWorkflowLifecycleOwner.updateLifecycle
```

Very hard to reproduce. 

- There's a variant in production that looks like it's related to config change, can't repro
- There's one I can make happen on demand via an espresso test that fires a deep link intent from a notification -- relaunches the activity with the UI pointed to a specific screen. (Can't repro by firing the same intent from adb.)

In both cases, the common elements seem to be that we're building the UI for the first time in a new activity, and that `AndroidView {}` is involved. Debugger reveals a missing call to `SavedStateRegistry.consumeRestoredStateForKey`.

Version info:

```
  lifecycleVersion = '2.5.1'

  composeRuntimeVersion = '1.4.3'
  composeFoundationVersion = '1.4.3'
  composeUiVersion = '1.4.3'
  composeAnimationVersion = '1.4.3'
  composeMaterialVersion = '1.1.0-rc01'

  kotlinVersion = getGradleProperty('square.kotlinVersion', '1.8.10')
  composeCompilerVersion = getGradleProperty('square.composeCompilerVersion', '1.4.4')
```

### PR DESCRIPTION
**Pull request by rjrjr**
If the very first rendering would instantiate `Dialog` windows, their content views were getting attached before the `Activity`'s content view. This would cause us to restore saved view state in the wrong order. If a `ComposeView` is in a `Dialog` in this situation, we would crash with an `IllegalStateException` from `SavedStateRegistry.consumeRestoredStateForKey`.

The fix is for `LayeredDialogSessions` and `DialogCollator` to conspire to decouple created `Dialog` instances from showing them the first time. Normally we go ahead and do both at once. But if `LayeredDialogSessions.update` is called before the corresponding `BodyAndOverlaysContainer` view is attached to the `Activity` window, we defer showing until it is.

Fixes #1001

### CODE REVIEW

**Comment by rjrjr** [comment]
This probably won't play nicely with `DialogCollator` as is.

**Comment by rjrjr** [comment]
> This probably won't play nicely with `DialogCollator` as is.

Confirmed, dialogs can re-open in the wrong order on config change. Shouldn't be a hard fix though. Just have the outermost container view put something in the view environment telling children to do nothing, and then make it the only one to update when the attach event comes.

Special bonus: this breaks every method in `DialogIntegrationTest`, even though the _Nested Overlays_ sample works fine manually (outside of config change).

File: workflow-ui/core-android/src/androidTest/java/com/squareup/workflow1/ui/container/DialogIntegrationTest.kt [hunk 1]
```diff
@@ -79,12 +91,14 @@ internal class DialogIntegrationTest {
 
     scenario.onActivity { activity ->
       val root = WorkflowLayout(activity)
+      activity.setContentView(root)
```
Comment (rjrjr) [inline workflow-ui/core-android/src/androidTest/java/com/squareup/workflow1/ui/container/DialogIntegrationTest.kt:94]: Oops, these tests were never actually attaching anything to the activity window. Now they do.

**Comment by rjrjr** [comment]
> Special bonus: this breaks every method in `DialogIntegrationTest`, even though the _Nested Overlays_ sample works fine manually (outside of config change).

Derp. That test was never actually callint `Activity.setContentView()`. (It doesn't run against the sample app, that's a different test.)

**Comment by rjrjr** [comment]
Realizing that in the recursive case, nested instances will always defer and replay for no reason. That seems bad. Could be why the performance shard "broke" (actually reported an unexpected improvement in render count).

**Comment by rjrjr** [comment]
This works, but under the hood it's a pretty drastic change to the order in which a UI hierarchy is updated -- a parent view can no longer assume that children will update synchronously, at least once an `Overlay` gets into the path. E.g. `BackButtonScreen` relies on this convention to ensure that children will stack their handlers before or after the parent's own, based on `BackButtonScreen.shadow`.

Of course this is a pretty janky, brittle mechanism, only in use in a few spots. Maybe this is the moment to improve those spots? Maybe we can find a fix to this attachment order problem that covers the whole tree, instead of just `LayeredDialogSessions`?

**Comment by rjrjr** [comment]
Ideally we would build the `Dialog`s first and then show them all at once, but that's simply not an option -- there are calls that it is unsafe to make on a `Dialog`'s `DecorView` before `show()`.

**Comment by rjrjr** [comment]
Could try to make `WorkflowLifecycleOwner` refuse to move to `RESUMED` before it is attached? Hard to imagine that won't break 500 other things. And maybe this fantasy of "children will update exactly and only when their parents say to" is already doomed by Compose.

**Comment by rjrjr** [comment]
> Could try to make `WorkflowLifecycleOwner` refuse to move to `RESUMED` before it is attached? Hard to imagine that won't break 500 other things. And maybe this fantasy of "children will update exactly and only when their parents say to" is already doomed by Compose.

Doesn't change anything, they're basically always attached.

**Comment by rjrjr** [comment]
> Realizing that in the recursive case, nested instances will always defer and replay for no reason. That seems bad. Could be why the performance shard "broke" (actually reported an unexpected improvement in render count).

Untrue, the new code is only firing in the problem case -- bootstrapping an entire view tree that includes dialog windows.

**Comment by rjrjr** [comment]
Well now.

That "always builds or updates all the things at once and in the expected order" invariant is a lot harder to live without than I realized.

Trying a new approach, which is maybe simpler and less fragile anyway. Basically, if we're not attached to a window when building dialogs, the only thing we defer until attach time is showing them -- we build them all immediately, just like today.

`DialogCollator` actually makes that very simple. Now to see if this approach still prevents the `IllegalStateException` from `consumeRestoredStateForKey`… 🤞

**Comment by rjrjr** [comment]
OMFG it works.

**Comment by rjrjr** [comment]
It works it works it works it works. For the problems that I know about. Can't wait to see what it breaks instead!

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/BodyAndOverlaysContainer.kt [hunk 2]
```diff
@@ -84,11 +84,11 @@ internal class BodyAndOverlaysContainer @JvmOverloads constructor(
   }
 
   override fun dispatchTouchEvent(event: MotionEvent): Boolean {
-    return !dialogs.allowEvents || super.dispatchTouchEvent(event)
+    return !dialogs.allowContentEvents || super.dispatchTouchEvent(event)
```
Comment (rjrjr) [inline workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/BodyAndOverlaysContainer.kt:87]: Unrelated method rename to try to make it clearer that this is strictly about event handling in the activity window, not the dialogs.

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/DialogCollator.kt [hunk 3]
```diff
@@ -60,19 +60,29 @@ internal class DialogSessionUpdate(
  * and [DialogCollator.scheduleUpdates]
  *
  * @param existingSessions [DialogSession] instances that were running before the pending update
+ *
+ * @param onRootUpdateFinished honored only for the outermost [LayeredDialogSessions] caller.
+ * If provided, called with the complete set of [DialogSession] created by
+ * [DialogCollator.scheduleUpdates], not just those of the client identified by [id].
+ * https://github.com/square/workflow-kotlin/issues/1001
```
Comment (rjrjr) [inline workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/DialogCollator.kt:67]: This URL isn't really useful here. It's already in the comments that are at the heart of the full fix.

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/DialogSession.kt [hunk 4]
```diff
@@ -125,7 +127,18 @@ internal class DialogSession(
         }
       }
     }
+  }
+
+  /**
+   * One time call to shows the managed [Dialog][OverlayDialogHolder.dialog] for the first time.
+   * Called after [initNewDialog] and [destroyDialog]
+   *
+   * See also [setVisible], used to dismiss and re-show and existing one.
```
Comment (rjrjr) [inline workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/DialogSession.kt:136]:
```suggestion
   * One time call to show the managed [Dialog][OverlayDialogHolder.dialog] for the first time.
   * Called between [initNewDialog] and [destroyDialog].
   *
   * See also [setVisible], used to dismiss and re-show an existing one.
```

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/LayeredDialogSessions.kt [hunk 5]
```diff
@@ -113,7 +113,34 @@ public class LayeredDialogSessions private constructor(
 
   private var sessions: List<DialogSession> = emptyList()
 
-  public var allowEvents: Boolean = true
+  /**
+   * Reflects whether [onAttachedToWindow] has been called yet, so that
+   * we can avoid creating `Dialog` windows before the `Activity` window
```
Comment (rjrjr) [inline workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/LayeredDialogSessions.kt:118]:
```suggestion
   * we can avoid [showing][showNewDialog] `Dialog` windows before the `Activity` window
```

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/LayeredDialogSessions.kt [hunk 6]
```diff
@@ -113,7 +113,34 @@ public class LayeredDialogSessions private constructor(
...
+   * is true, holds on to the set of all [DialogSession] to be shown at
+   * attach time, instead of immediately. Necessary to ensure that view state
+   * is restored in the correct order -- the Activity contentView must be attached
+   * to its window before those of any Dialog instance.
+   *
+   * Note that this is a superset of [sessions], includes built by
+   * any nested [LayeredDialogSessions] instances during recursive [update]
+   * calls.
+   *
+   * https://github.com/square/workflow-kotlin/issues/1001
```
Comment (rjrjr) [inline workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/LayeredDialogSessions.kt:134]:
```suggestion
   * Set by an outermost instance only. If we are in a root [update] call before 
   * [attached] is true, holds on to the set of all [DialogSession] to be 
   * [shown][showNewDialog] at attach time, instead of immediately. Necessary to
   * ensure that view state is restored in the correct order -- the `Activity`
   * `contentView` must be attached to its window before that of any `Dialog`.
   *
   * Note that this is a superset of [sessions], includes built by
   * any nested [LayeredDialogSessions] instances during recursive [update]
   * calls.
   *
   * https://github.com/square/workflow-kotlin/issues/1001
```

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/BodyAndOverlaysContainer.kt (hunk 2 above)
Comment (steve-the-edwards) [reply workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/BodyAndOverlaysContainer.kt:87]: Why `allowContentEvents` and not `allowBodyEvents`? I think Body would help me understand what you mean.

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/LayeredDialogSessions.kt [hunk 7]
```diff
@@ -113,7 +113,35 @@ public class LayeredDialogSessions private constructor(
...
+   * Note that this is a superset of [sessions], also includes sessions built by
+   * any nested [LayeredDialogSessions] instances during recursive [update]
+   * calls.
+   *
+   * https://github.com/square/workflow-kotlin/issues/1001
+   */
+  private var deferredShow: List<DialogSession>? = null
+
+  /**
+   * Clients should ignore UI events targeting their [content][ScreenOverlay.content]
```
Comment (steve-the-edwards) [inline workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/LayeredDialogSessions.kt:140]: so this is where the `content` naming comes from? Hmm. How do I map body to content? are they equivalent? 'Body' is the container for 'content'?

**Review by steve-the-edwards — COMMENTED** [review]
Nice! A few naming questions as usual 😄

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/BodyAndOverlaysContainer.kt (hunk 2 above)
Comment (rjrjr) [reply workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/BodyAndOverlaysContainer.kt:87]: I wrestled with that. I went with `content` because it matches `ScreenOverlay.content`, which in turn comes from the `Wrapper` interface.  But really they're both still ambiguous, aren't they -- dialog content? dialog body?

How about `allowBaseEvents`? That would match the `updateBase` param to `LayeredDialogSessions.update`.

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/DialogSession.kt [hunk 8]
```diff
@@ -87,10 +88,11 @@ internal class DialogSession(
   private val KeyEvent.isBackPress: Boolean
     get() = (keyCode == KEYCODE_BACK || keyCode == KEYCODE_ESCAPE) && action == ACTION_UP
 
-  fun initAndShowDialog(
-    parentLifecycleOwner: LifecycleOwner,
-    initialEnvironment: ViewEnvironment
-  ) {
+  /**
+   * One time call to set up our brand new [OverlayDialogHolder] instance.
```
[the remark this answers is not in the document]
Comment (rjrjr) [reply workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/DialogSession.kt:92]: That gets into another level of API inconsistency. `holder.show` is public, `OverlayDialogHolder.show`, and it parallel `ScreenViewHolder.show`. The is definitely an awkward seam, but it's all in non-public code. 

Basically, `Dialog.show()` conflicts with our `show(someRendering, environment)` convention. But it's only us on the Workflow team who take the cognitive hit, b/c feature code never gets anywhere near `Dialog.show()` or `Dialog.dismiss()`.

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/LayeredDialogSessions.kt (hunk 7 above)
Comment (rjrjr) [reply workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/LayeredDialogSessions.kt:140]: Oh, derp: and that kdoc is TOTALLY WRONG! Link should be to `BodyAndOverlays.content`!

Comment (rjrjr) [reply workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/LayeredDialogSessions.kt:140]: Tell you what, let's decouple this naming conversation from the ordering fix. Maybe even move it upstream.

Comment (rjrjr) [reply workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/LayeredDialogSessions.kt:140]:
```kotlin
  /**
   * While this is true, clients should ignore UI events targeting the
   * [body][BodyAndOverlaysScreen.body] view beneath the
   * [Dialog][android.app.Dialog] windows they manage. It reflects
   * that a [ModalOverlay] is (or soon will be) showing over the body screen.
   */
  public var allowBodyEvents: Boolean = true
```

File: samples/nested-overlays/src/main/java/com/squareup/sample/nestedoverlays/NestedOverlaysWorkflow.kt [hunk 9]
```diff
@@ -46,36 +48,44 @@ object NestedOverlaysWorkflow : StatefulWorkflow<Unit, State, Nothing, Screen>()
...
-          Button(
-            name = R.string.close,
-            onClick = context.eventHandler { state = state.copy(showOuterSheet = false) }
+        BackButtonScreen(
+          ButtonBar(
+            Button(
+              name = R.string.close,
+              onClick = close
+            ),
+            context.toggleInnerSheetButton(renderState),
```
[the remark this answers is not in the document]
Comment (rjrjr) [reply samples/nested-overlays/src/main/java/com/squareup/sample/nestedoverlays/NestedOverlaysWorkflow.kt:59]: Oops, nope, can't do that either.

[the remark this answers is not in the document]
Comment (rjrjr) [reply samples/nested-overlays/src/main/java/com/squareup/sample/nestedoverlays/NestedOverlaysWorkflow.kt:59]: Combination of `vararg` and default values is pretty hard to work with, I don't think I can make this better.

**Comment by rjrjr** [comment]
@steve-the-edwards PTAL, adopted most of your naming fixes.

File: samples/nested-overlays/src/androidTest/java/com/squareup/sample/nestedoverlays/NestedOverlaysAppTest.kt [hunk 10]
```diff
@@ -56,6 +57,28 @@ class NestedOverlaysAppTest {
     onBottomCoverEverything().assertNotDisplayed()
   }
 
+  @Test fun backButtonWorks() {
+    onTopCoverEverything().perform(click())
+    onView(withText("Cover Body")).inRoot(isDialog()).perform(click())
```
[the remark this answers is not in the document]
Comment (rjrjr) [reply samples/nested-overlays/src/androidTest/java/com/squareup/sample/nestedoverlays/NestedOverlaysAppTest.kt:62]: I don't know why, but I always find that makes tests harder for me to read.

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/BodyAndOverlaysContainer.kt (hunk 2 above)
Comment (rjrjr) [reply workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/container/BodyAndOverlaysContainer.kt]: See insane stream of consciousness below, `allowBodyEvents` and `updateBody()` FTW.

**Review by ijwhelan — APPROVED** [review]
Still a novice at Workflow internals but I'm not seeing any obvious issues, changes make sense to me.
