### PR TITLE
`View.backPressHandler` memory leak fix.

### LINKED ISSUE #889: BackPressHandler leaks the view after its detached
HandleBackPressWhenAttached adds a OnBackPressedCallback  callback to the OnBackPressedDispatcherOwner implemented by the context of the view, i.e. in this case the activity. 

The leak trace indicates that the OnBackPressedCallback is still held by the activity even though the view itself is detached.

https://github.com/square/workflow-kotlin/blob/8c524dbabaec6e61fc4034baf40d47b9e6ffeea4/workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/BackPressHandler.kt#L89

We probably shouldn't keep the callback around (and its reference to the view) after the view has been detached.

Leaktrace

```
┬───
│ GC Root: System class
│
├─ android.view.inputmethod.InputMethodManager class
│    Leaking: NO (InputMethodManager↓ is not leaking and a class is never leaking)
│    ↓ static InputMethodManager.sInstance
├─ android.view.inputmethod.InputMethodManager instance
│    Leaking: NO (DevDrawerDraggerLayout↓ is not leaking and InputMethodManager is a singleton)
│    ↓ InputMethodManager.mNextServedView
├─ com.squareup.development.drawer.DevDrawerDraggerLayout instance
│    Leaking: NO (SquidSystemUiActivity↓ is not leaking and View attached)
│    View is part of a window view hierarchy
│    View.mAttachInfo is not null (view attached)
│    View.mID = R.id.development_drawer_dragger
│    View.mWindowAttachCount = 1
│    mContext instance of com.squareup.squid.systemuiapp.ui.SquidSystemUiActivity with mDestroyed = false
│    ↓ View.mContext
├─ com.squareup.squid.systemuiapp.ui.SquidSystemUiActivity instance
│    Leaking: NO (LifecycleRegistry↓ is not leaking and Activity#mDestroyed is false)
│    context instance of com.squareup.squid.systemuiapp.ui.SquidSystemUiActivity with mDestroyed = false
│    mApplication instance of com.squareup.squid.systemuiapp.DevSquidSystemUiApplication
│    mBase instance of androidx.appcompat.view.ContextThemeWrapper
│    ↓ ComponentActivity.mLifecycleRegistry
├─ androidx.lifecycle.LifecycleRegistry instance
│    Leaking: NO (mState is not DESTROYED)
│    mState = CREATED
│    ↓ LifecycleRegistry.mObserverMap
│                        ~~~~~~~~~~~~
├─ androidx.arch.core.internal.FastSafeIterableMap instance
│    Leaking: UNKNOWN
│    Retaining 41.5 kB in 765 objects
│    ↓ FastSafeIterableMap[key()]
│                         ~~~~~~~
├─ androidx.activity.OnBackPressedDispatcher$LifecycleOnBackPressedCancellable instance
│    Leaking: UNKNOWN
│    Retaining 40.0 kB in 707 objects
│    ↓ OnBackPressedDispatcher$LifecycleOnBackPressedCancellable.mOnBackPressedCallback
│                                                                ~~~~~~~~~~~~~~~~~~~~~~
├─ com.squareup.workflow1.ui.HandleBackPressWhenAttached$onBackPressedCallback$1 instance
│    Leaking: UNKNOWN
│    Retaining 39.9 kB in 705 objects
│    Anonymous subclass of androidx.activity.OnBackPressedCallback
│    ↓ HandleBackPressWhenAttached$onBackPressedCallback$1.this$0
│                                                          ~~~~~~
├─ com.squareup.workflow1.ui.HandleBackPressWhenAttached instance
│    Leaking: UNKNOWN
│    Retaining 39.9 kB in 701 objects
│    ↓ HandleBackPressWhenAttached.view
│                                  ~~~~
├─ android.widget.LinearLayout instance
│    Leaking: YES (View detached yet still part of window view hierarchy)
│    Retaining 39.9 kB in 700 objects
│    View is part of a window view hierarchy
│    View.mAttachInfo is null (view detached)
│    View.mID = R.id.parent_panel
│    View.mWindowAttachCount = 1
│    mContext instance of com.squareup.squid.systemuiapp.ui.SquidSystemUiActivity with mDestroyed = false
│    ↓ View.mParent
├─ android.widget.FrameLayout instance
│    Leaking: YES (LinearLayout↑ is leaking and View detached yet still part of window view hierarchy)
│    Retaining 21.8 kB in 407 objects
│    View is part of a window view hierarchy
│    View.mAttachInfo is null (view detached)
│    View.mID = R.id.null
│    View.mWindowAttachCount = 1
│    mContext instance of android.view.ContextThemeWrapper, wrapping activity com.squareup.squid.systemuiapp.ui.SquidSystemUiActivity with mDestroyed = false
│    ↓ View.mParent
├─ android.widget.FrameLayout instance
│    Leaking: YES (FrameLayout↑ is leaking and View detached yet still part of window view hierarchy)
│    Retaining 20.6 kB in 387 objects
│    View is part of a window view hierarchy
│    View.mAttachInfo is null (view detached)
│    View.mWindowAttachCount = 1
│    mContext instance of android.view.ContextThemeWrapper, wrapping activity com.squareup.squid.systemuiapp.ui.SquidSystemUiActivity with mDestroyed = false
│    ↓ View.mParent
╰→ com.android.internal.policy.DecorView instance
​     Leaking: YES (ObjectWatcher was watching this because com.android.internal.policy.DecorView received View#onDetachedFromWindow() callback)
​     Retaining 18.8 kB in 364 objects
​     key = a174b29b-52f2-4989-a189-971edc493e4a
​     watchDurationMillis = 242736
​     retainedDurationMillis = 237731
​     View not part of a window view hierarchy
​     View.mAttachInfo is null (view detached)
​     View.mWindowAttachCount = 1
​     mContext instance of android.view.ContextThemeWrapper, wrapping activity com.squareup.squid.systemuiapp.ui.SquidSystemUiActivity with mDestroyed = false
```

https://app.bugsnag.com/square-inc/register-android-dev-leaks/errors/6262b5b5473e980008b4bce8

### PR DESCRIPTION
**Pull request by rjrjr**
We now strictly require that a `ViewTreeLifecycleOwner` can be found so that we can be certain of getting a callback to remove the `OnBackPressedCallback` from the `OnBackPressedDispatcher`. We also null out the guts of the callback while the `View` is detached, to be doubly sure not to leak anything even if the `ViewTreeLifecycleOwner` is misbehaving.

Fixes #889.

### CODE REVIEW

File: workflow-ui/core-android/src/androidTest/java/com/squareup/workflow1/ui/BackPressedHandlerTest.kt [hunk 1]
```diff
@@ -0,0 +1,117 @@
...
+
+      activity.setContentView(view)
+      assertThat(viewHandlerCount).isEqualTo(0)
+
+      activity.onBackPressed()
+      assertThat(viewHandlerCount).isEqualTo(1)
+    }
+  }
+
+  @Test fun itWorksWhenHandlerIsAddedAfterAttach() {
```
Comment (rjrjr) [inline workflow-ui/core-android/src/androidTest/java/com/squareup/workflow1/ui/BackPressedHandlerTest.kt:47]: - [ ] Oops, this test is identical to the one above it.

**Review by pyricau — APPROVED** [review]

File: workflow-ui/core-android/src/androidTest/java/com/squareup/workflow1/ui/OnBackPressedDispatcherSpy.java [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+
+public class OnBackPressedDispatcherSpy {
+  private final OnBackPressedDispatcher dispatcher;
+
+  public OnBackPressedDispatcherSpy(OnBackPressedDispatcher dispatcher) {
+    this.dispatcher = dispatcher;
+  }
+
+  public ArrayDeque<OnBackPressedCallback> callbacks() {
+    return dispatcher.mOnBackPressedCallbacks;
```
Comment (helios175) [inline workflow-ui/core-android/src/androidTest/java/com/squareup/workflow1/ui/OnBackPressedDispatcherSpy.java:13]: nit: Collection or List maybe?

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/BackPressHandler.kt [hunk 3]
```diff
@@ -21,79 +22,123 @@ public typealias BackPressHandler = () -> Unit
...
+    lifecycleOrNull?.removeObserver(this)
   }
 
   override fun onViewAttachedToWindow(attachedView: View) {
     require(view === attachedView)
-    onBackPressedCallback.isEnabled = true
+    lifecycleOrNull?.let { lifecycle ->
+      lifecycle.removeObserver(this)
+      lifecycleOrNull = null
+    }
```
Comment (helios175) [inline workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/BackPressHandler.kt:109]: nit:
```
lifecycleOrNull?.removeObserver(this)
lifecycleOrNull = null
```

Comment (helios175) [reply workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/BackPressHandler.kt:109]: In fact you can do
```
lifecycleOrNull?.removeObserver(this)
lifecycleOrNull = ViewTreeLifecycleOwner.get(view)?.lifecycle
```

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/androidx/WorkflowLifecycleOwner.kt [hunk 4]
```diff
@@ -112,9 +112,6 @@ internal class RealWorkflowLifecycleOwner(
   OnAttachStateChangeListener,
   LifecycleEventObserver {
 
-  /**
-   * Weak reference ensures that we don't leak the view.
-   */
```
Comment (helios175) [inline workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/androidx/WorkflowLifecycleOwner.kt:117]: LOL

**Review by helios175 — APPROVED** [review]
Not exactly sure how this fixes any leak, but looks correct.

techincally-correct

File: workflow-ui/core-android/src/androidTest/java/com/squareup/workflow1/ui/OnBackPressedDispatcherSpy.java (hunk 2 above)
Comment (rjrjr) [reply workflow-ui/core-android/src/androidTest/java/com/squareup/workflow1/ui/OnBackPressedDispatcherSpy.java:13]: I'm exposing the implementation of an Android class for testing purposes, I don't think there's a real need to abstract it.

**Comment by rjrjr** [comment]
> Not exactly sure how this fixes any leak, but looks correct.

The old code would register with `ViewTreeLifecycleOwner` immediately, IFF it was non-null. It frequently wasn't set yet, so `stop()` would never be called, and the callback would never be removed from the Jetpack dispatcher. Activity > Dispatcher > Detached Window, leak.
