### PR TITLE
Simpler, safer ViewEnvironment and ViewRegistry management.

### LINKED ISSUE #395: Merging ViewRegistries inside ViewEnvironments is a nightmare.
There are a couple of issues:

 * When you `plus()` two `ViewEnvironments`, entries are completely replaced, there are no merge hooks
 * When you `plus()` two `ViewRegistries`, if they have any redundant entries an exception is thrown

For the former, perhaps we can build optional merge hooks into `ViewEnvironmentKey`?

For the latter, I'm hard pressed to think of any bugs we have caught by throwing, but I can come up of lots of examples where we had to struggle mightily to work around it. How about if we document that entries in the registry on the right in a `ViewRegistry.plus()` call will clobber those on the left? We could offer a strict variant, or even default to it, but I can't really imagine when I'd use it.

### PR DESCRIPTION
**Pull request by rjrjr**
`ViewEnvironment(Map<ViewEnvironmentKey<*>, Any>)` makes it easy to build a
`ViewEnvironment` whose with values that don't match the type of the
`ViewEnvironmentKey`s. We deprecate it with an eye toward making it
non-public down the road. In its place we introduce `ViewEnvironment.EMPTY`,
and guide people to use it and the type safe `plus` operators.

We introduce a pattern of providing more `plus` operators with new environment
value types.

For `ViewRegistry`, in addition to the `plus` operator we provide a set of
`merge` methods, which finish the long overdue job of making it simpler to
mess with `ViewEnvironment` without stomping on `ViewRegistry` entries, and
to override them. `EnvironmentScreen.withRegistry` and `.withEnvironment` use
these.

Fixes #395. Replaces #630, reverted due to accidental merge.

### CODE REVIEW

**Review by steve-the-edwards — COMMENTED** [review]
Have not finished reviewing because paused thinking about why we can't have the + operator come in via an interface. Just fiddling with the variance to see if I can get it to work a la 

```

interface ViewEnvironmental

operator fun <T: ViewEnvironmental> ViewEnvironment.plus(value: T): ViewEnvironment =
  this + ViewEnvironment(mapOf(value::class to value))

```

which currently doesn't compile due to the variance of `value::class`

File: workflow-ui/core-common/src/main/java/com/squareup/workflow1/ui/ViewRegistry.kt [hunk 1]
```diff
@@ -102,10 +104,67 @@ public fun ViewRegistry(vararg bindings: Entry<*>): ViewRegistry =
...
+
+/**
+ * Merges the [ViewRegistry] of the receiver with [registry]. If there are conflicting entries,
+ * those in [registry] are preferred.
+ */
+@WorkflowUiExperimentalApi
+public infix fun ViewEnvironment.merge(registry: ViewRegistry): ViewEnvironment {
+  val oldReg = this[ViewRegistry]
+
+  val union = (oldReg.keys + registry.keys).asSequence()
```
Comment (rjrjr) [inline workflow-ui/core-common/src/main/java/com/squareup/workflow1/ui/ViewRegistry.kt:149]: Oops, this is a dup of the merge() method above. Should call that from here.

File: samples/compose-samples/src/main/java/com/squareup/sample/compose/textinput/App.kt [hunk 2]
```diff
@@ -1,4 +1,5 @@
 @file:OptIn(WorkflowUiExperimentalApi::class)
+@file:Suppress("FunctionName")
```
[the remark this answers is not in the document]
Comment (rjrjr) [reply samples/compose-samples/src/main/java/com/squareup/sample/compose/textinput/App.kt:2]: It's complaining about the capitalized function name. We don't _have_ to fail it, the build was green. I just hate IDE warnings.

**Comment by rjrjr** [comment]
> Have not finished reviewing because paused thinking about why we can't have the + operator come in via an interface. Just fiddling with the variance to see if I can get it to work a la
> 
> ```
> 
> interface ViewEnvironmental
> 
> operator fun <T: ViewEnvironmental> ViewEnvironment.plus(value: T): ViewEnvironment =
>   this + ViewEnvironment(mapOf(value::class to value))
> ```
> 
> which currently doesn't compile due to the variance of `value::class`

It's a fun problem space, isn't it? Really seems like `ViewEnvironment` could be spun out into its own microlibrary -- `com.block.polymap`.

I keep resisting the urge to create a general purpose mechanism for things to declare themselves mergable, b/c I strongly suspect that `ViewRegistry` will be the only use case forever.

**Comment by steve-the-edwards** [comment]
> Have not finished reviewing because paused thinking about why we can't have the + operator come in via an interface. ...

Blarg we'd be sacrificing one convenience/legibility helper for another. I think i'm rocking the boat too much here, but the idea would be to take your pattern of making the companion object the `ViewEnvironmentKey` (nice because it has only one initialization at class init time) and instead move it to an interface where we could then enforce the operations etc.

I think i'm trying to get back to the `ViewWrapper` that I (unhelpfully) nerd-sniped you into with the failed #606 .

Ok will stop trying to make this harder than it is 😊

**Comment by rjrjr** [comment]
Latest force-push makes the tests green.

`TicTacToeEspressoTest#showRenderingTagStaysFresh` was failing because it inadvertently exposed a wateful allocations -- when we started calling the new `merge` functions on every render pass, we were creating new instances of `CompositeViewRegistry` for no reason. I've added / restored some checks to return the existing `ViewEnvironment` or `ViewRegistry` when merging with an empty one.

I'll add some explicit coverage for that, seems worth being formal about it.

**Comment by rjrjr** [comment]
@steve-the-edwards PTAL, I've added a commit that adds the missing test coverage for that optimization, and adds a few more such `if (this.isEmpty()) return that` cases.

File: workflow-ui/core-common/src/main/java/com/squareup/workflow1/ui/ViewRegistry.kt [hunk 3]
```diff
@@ -102,10 +104,70 @@ public fun ViewRegistry(vararg bindings: Entry<*>): ViewRegistry =
...
+}
+
+/**
+ * Merges the [ViewRegistry] of the receiver with [registry]. If there are conflicting entries,
+ * those in [registry] are preferred.
+ */
 @WorkflowUiExperimentalApi
-public operator fun ViewRegistry.plus(binding: Entry<*>): ViewRegistry =
-  this + ViewRegistry(binding)
+public infix fun ViewEnvironment.merge(registry: ViewRegistry): ViewEnvironment {
```
Comment (steve-the-edwards) [inline workflow-ui/core-common/src/main/java/com/squareup/workflow1/ui/ViewRegistry.kt:153]: Beware I think once we start having mixed typed operators things can sometimes get confusing - this is the case for `CoroutineContext` which maps scope, dispatcher, name etc. in a very similar way to this. 90% of the time things just 'work' and work in a quick and satisfying way, but sometimes when reasoning about it it can get confusing how things overlap.

**Review by steve-the-edwards — APPROVED** [review]
