### PR TITLE
ComposeViewTreeIntegrationTest clean up, fixes

### LINKED ISSUE #800: ComposeViewTreeIntegrationTest#composition_is_restored_in_modal_after_config_change failing
Consistently failing on both Pixel 5 emulator API 32 and real physical Pixel 6 API 32.

Tested with animation enabled and disabled on emulator.

```
java.lang.IllegalStateException: You can consumeRestoredStateForKey only after super.onCreate of corresponding component
at androidx.savedstate.SavedStateRegistry.consumeRestoredStateForKey(SavedStateRegistry.java:77)
at androidx.compose.ui.platform.DisposableSaveableStateRegistry_androidKt.DisposableSaveableStateRegistry(DisposableSaveableStateRegistry.android.kt:75)
at androidx.compose.ui.platform.DisposableSaveableStateRegistry_androidKt.DisposableSaveableStateRegistry(DisposableSaveableStateRegistry.android.kt:54)
at androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:105)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:157)
at androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:156)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:107)
at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:34)
```

### PR DESCRIPTION
**Pull request by rjrjr**
Three commits:

### Undoes view tag wonkiness in ComposeViewTreeIntegrationTest
It was left over from an earlier draft of ScreenViewFactory.

### Eliminates workarounds for old Compose testing issue
https://issuetracker.google.com/issues/179455327 was fixed.

### Fixes botched test `composition_is_restored_in_modal_after_config_change`.

I converted it wrong, putting what was supposed to be the modal content into the body / activity instead. So the test was passing vaccuously, and even better, failing with an obscure `SavedStateRegistry.consumeRestoredStateForKey` exception on higher API levels.

Fixes #800.

### CODE REVIEW

File: workflow-ui/compose/src/androidTest/java/com/squareup/workflow1/ui/compose/ComposeViewTreeIntegrationTest.kt [hunk 1]
```diff
@@ -372,7 +372,9 @@ internal class ComposeViewTreeIntegrationTest {
     // Show first screen to initialize state.
     scenario.onActivity {
       it.setRendering(
-        BodyAndModalsScreen<Screen, Overlay>(BackStackScreen(EmptyRendering, firstScreen))
+        BodyAndModalsScreen(
```
Comment (rjrjr) [inline workflow-ui/compose/src/androidTest/java/com/squareup/workflow1/ui/compose/ComposeViewTreeIntegrationTest.kt:375]: This is the fix for #800.

File: workflow-ui/compose/src/androidTest/java/com/squareup/workflow1/ui/compose/ComposeViewTreeIntegrationTest.kt [hunk 2]
```diff
@@ -588,24 +589,31 @@ internal class ComposeViewTreeIntegrationTest {
...
-        }
+      var lastCompositionStrategy = initialRendering.disposeStrategy
+
+      return ComposeView(context).let { view ->
+        lastCompositionStrategy?.let(view::setViewCompositionStrategy)
+
+        ScreenViewHolder(initialEnvironment, view) { rendering, _ ->
+          if (rendering.disposeStrategy != lastCompositionStrategy) {
+            lastCompositionStrategy = rendering.disposeStrategy
+            lastCompositionStrategy?.let { view.setViewCompositionStrategy(it) }
```
Comment (vgonda) [inline workflow-ui/compose/src/androidTest/java/com/squareup/workflow1/ui/compose/ComposeViewTreeIntegrationTest.kt:600]: Oh! I just started looking into `setViewCompositionStrategy` with some test leaks we're getting. I'm gonna be looking into if we're setting this in prod and why

**Review by vgonda — APPROVED** [review]

**Review by steve-the-edwards — APPROVED** [review]
