### PR TITLE
Android wrappers for renderWorkflowIn deprecate setContentWorkflow.

### LINKED ISSUE #162: RecyclerView's scroll position not restored after config change when using Jetpack navigation
I'm again trying to integrate workflow with Jetpack navigation / fragment 😅  and found an issue where the `RecyclerView`'s scroll position is not restored after config change.

I've again extended the [`hello-workflow-fragment` sample](https://github.com/ychescale9/workflow-kotlin/tree/yc/jetpack-nav-recyclerview-scroll-position/samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment) to reproduce this:

1. Scroll the list so some items at the top are off the screen
2. Rotate the screen
3. The 1st item appears at the top of the list

This can also be reproduced by just using `FragmentViewContainer` to inflate the fragment so this might not necessarily be Jetpack navigation:

```
<androidx.fragment.app.FragmentContainerView xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:id="@+id/helloWorkflowFragment"
    android:name="com.squareup.sample.helloworkflowfragment.HelloWorkflowFragment"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:orientation="vertical"
    tools:context=".HelloWorkflowFragmentActivity"
    />


```

### LINKED ISSUE #268: Remove use of deprecated lastCustomNonConfigurationInstance from samples
`lastCustomNonConfigurationInstance` was deprecated in appcompat 1.1.0 (#602).

### PR DESCRIPTION
**Pull request by rjrjr**
Deprecates `WorkflowRunner` and related classes, functions in favor of a single
Android-specific overload of `renderWorkflowIn`. Rather than maintain our own
complex `ViewModel` implementation, encourage authors to create their own.

See copious kdoc for details.

Closes #162, closes #268.

- [x] Update all samples
- [x] Update tutorials
- [ ] LG from @bnvinay92 
- [ ] LG from @SalvatoreT

### CODE REVIEW

**Comment by rjrjr** [comment]
@steve-the-edwards @zach-klippenstein Still a draft, but can I have a sanity check before I finish it?

File: samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloWorkflowActivity.kt [hunk 1]
```diff
@@ -1,21 +1,35 @@
...
   override fun onCreate(savedInstanceState: Bundle?) {
     super.onCreate(savedInstanceState)
-    setContentWorkflow {
-      WorkflowRunner.Config(
-          HelloWorkflow,
-          interceptors = listOf(SimpleLoggingWorkflowInterceptor())
-      )
-    }
+
+    val model: HelloViewModel by viewModels()
```
Comment (rjrjr) [inline samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloWorkflowActivity.kt:20]: Oops, broke the back button

Comment (rjrjr) [reply samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloWorkflowActivity.kt:20]: How?

Comment (rjrjr) [reply samples/hello-workflow/src/main/java/com/squareup/sample/helloworkflow/HelloWorkflowActivity.kt:20]: No I didn't, that was never part of this sample.

File: samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloWorkflowFragment.kt [hunk 2]
```diff
@@ -1,15 +1,40 @@
...
+import com.squareup.workflow1.ui.renderWorkflowIn
+import kotlinx.coroutines.flow.StateFlow
 
 @OptIn(WorkflowUiExperimentalApi::class)
-class HelloWorkflowFragment : WorkflowFragment<Unit, Nothing>() {
-  override fun onCreateWorkflow(): WorkflowRunner.Config<Unit, Nothing> {
-    return WorkflowRunner.Config(
-        HelloWorkflow, interceptors = listOf(SimpleLoggingWorkflowInterceptor())
-    )
+class HelloWorkflowFragment : Fragment() {
```
Comment (rjrjr) [inline samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloWorkflowFragment.kt:18]: @bnvinay92 WDYT about using this instead of `WorkflowFragment`? Planning to deprecate that, and delete it from the beta.

**Review by zach-klippenstein — COMMENTED** [review]
Looks really good. Slightly more boilerplate, but it's in the right place, and much less magic than what we had before.

File: samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloWorkflowFragment.kt [hunk 3]
```diff
@@ -1,15 +1,40 @@
...
+  private val model: HelloViewModel by activityViewModels()
```
Comment (steve-the-edwards) [inline samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloWorkflowFragment.kt:19]: Confusing that you scoped the ViewModel to the activity and not the fragment here?? From what I can tell in this example we have a single Fragment and not a shared ViewModel. So we should be delegating to `by viewModels()` here and scoping this to the fragment no?

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/AndroidRenderWorkflow.kt [hunk 4]
```diff
@@ -0,0 +1,121 @@
...
+  interceptors: List<WorkflowInterceptor> = emptyList(),
+  onOutput: suspend (OutputT) -> Unit = {}
+): StateFlow<RenderingT> {
+  val restoredSnap = savedStateHandle?.get<PickledWorkflow>(KEY)?.snapshot
+  val renderingsAndSnapshots = renderWorkflowIn(
+    workflow, scope, props, restoredSnap, interceptors, onOutput
+  )
+
+  return renderingsAndSnapshots
+    .onEach { savedStateHandle?.set(KEY, PickledWorkflow(it.snapshot)) }
```
Comment (steve-the-edwards) [inline workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/AndroidRenderWorkflow.kt:116]: lol @`PickledWorkflow` - do we already use this concept in the examples?

**Review by steve-the-edwards — CHANGES_REQUESTED** [review]

File: samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloWorkflowFragment.kt (hunk 3 above)
Comment (rjrjr) [reply samples/hello-workflow-fragment/src/main/java/com/squareup/sample/helloworkflowfragment/HelloWorkflowFragment.kt:19]: Yeah, that was lazy. `by viewModels()` doesn't work for `Fragment` of course, because that would be too useful.

- [ ] Fix scoping in `Fragment` sample

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/AndroidRenderWorkflow.kt (hunk 4 above)
Comment (rjrjr) [reply workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/AndroidRenderWorkflow.kt:116]: No, it's internal, and I intend it to stay that way.

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/WorkflowRunnerViewModel.kt [hunk 5]
```diff
@@ -65,23 +46,23 @@ internal class WorkflowRunnerViewModel<OutputT>(
       }
 
       val renderingsAndSnapshots = renderWorkflowIn(
-          config.workflow, scope, props,
-          initialSnapshot = snapshot,
-          interceptors = config.interceptors
+        config.workflow, scope, props,
```
Comment (SalvatoreT) [inline workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/WorkflowRunnerViewModel.kt:49]: nit: while we're here, can you please name these parameters?

**Comment by SalvatoreT** [comment]
Can you please post an example of `#renderWorkflowInAndroid` in use? I'm having trouble figuring out what I'd do with the `scope` parameter.

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/WorkflowRunnerViewModel.kt (hunk 5 above)
Comment (rjrjr) [reply workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/WorkflowRunnerViewModel.kt:49]: > Can you please post an example of `#renderWorkflowInAndroid` in use? I'm having trouble figuring out what I'd do with the `scope` parameter.

I've already deleted it. Thought I had a use case where I couldn't use `ViewModel`, but I don't.

**Comment by rjrjr** [comment]
> Can you please post an example of `#renderWorkflowInAndroid` in use? I'm having trouble figuring out what I'd do with the `scope` parameter.

I've already deleted it. Thought I had a use case where I couldn't use `ViewModel`, but I don't.

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/WorkflowRunnerViewModel.kt (hunk 5 above)
Comment (rjrjr) [reply workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/WorkflowRunnerViewModel.kt:49]: Not much point, because the goal is to deprecate this entire mess. Or do you mean the params to `renderWorkflowIn`? Suggestions?

Comment (SalvatoreT) [reply workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/WorkflowRunnerViewModel.kt:49]: Oh, I just mean that some variables have their argument names next to them (e.g. `initialSnapshot = snapshot`) and the first three parameters don't.

**Comment by rjrjr** [comment]
I'm still working on the tutorials, but otherwise I think this is in its final form and ready for review.

File: samples/containers/app-raven/src/main/java/com/squareup/sample/ravenapp/RavenActivity.kt [hunk 6]
```diff
@@ -20,19 +28,17 @@ class RavenActivity : AppCompatActivity() {
...
-        )
-      },
-      onResult = { finish() }
+
+    val model: RavenModel by viewModels()
+    setContentView(
+      WorkflowLayout(this).apply { start(model.renderings, viewRegistry) }
     )
+
+    lifecycle.coroutineScope.launch {
```
Comment (rjrjr) [inline samples/containers/app-raven/src/main/java/com/squareup/sample/ravenapp/RavenActivity.kt:37]: Use silly `lifecycleScope` method for consistency.

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/AndroidRenderWorkflow.kt [hunk 7]
```diff
@@ -0,0 +1,286 @@
...
+    .onEach { savedStateHandle?.set(KEY, PickledTreesnapshot(it.snapshot)) }
+    .map { it.rendering }
+    .stateIn(scope, Eagerly, renderingsAndSnapshots.value.rendering)
+}
+
+/**
+ * An Android `ViewModel`-friendly wrapper for [com.squareup.workflow1.renderWorkflowIn],
+ * for use with a [workflow] that requires one input value ([prop]) to run.
+ *
+ * For example, for a workflow that uses [android.content.Intent] as its `PropsT` type,
```
Comment (rjrjr) [inline workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/AndroidRenderWorkflow.kt:194]: Example is wrong.

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/AndroidRenderWorkflow.kt [hunk 8]
```diff
@@ -0,0 +1,286 @@
...
+ * used to forward outputs to a [Flow][kotlinx.coroutines.flow.Flow]
+ * or [Channel][kotlinx.coroutines.channels.Channel], for example.
+ *
+ * @return
+ * A [StateFlow] of [RenderingT]s that will emit any time the root workflow creates a new
+ * rendering.
+ */
+@WorkflowUiExperimentalApi
+@OptIn(ExperimentalCoroutinesApi::class, ExperimentalWorkflowApi::class)
+public fun <PropsT, OutputT, RenderingT> renderWorkflowIn(
```
Comment (rjrjr) [inline workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/AndroidRenderWorkflow.kt:171]: Should move this above the `props` version.

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/AndroidRenderWorkflow.kt (hunk 7 above)
Comment (rjrjr) [reply workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/AndroidRenderWorkflow.kt:194]: Should move this above the `props` version.

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/AndroidRenderWorkflow.kt [hunk 9]
```diff
@@ -0,0 +1,286 @@
...
+  workflow: Workflow<PropsT, OutputT, RenderingT>,
+  scope: CoroutineScope,
+  prop: PropsT,
+  savedStateHandle: SavedStateHandle? = null,
+  interceptors: List<WorkflowInterceptor> = emptyList(),
+  onOutput: suspend (OutputT) -> Unit = {}
+): StateFlow<RenderingT> {
```
Comment (rjrjr) [inline workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/AndroidRenderWorkflow.kt:274]: Unnecessary copy / paste here, call the other method.

File: samples/containers/app-raven/src/main/java/com/squareup/sample/ravenapp/RavenActivity.kt [hunk 10]
```diff
@@ -20,19 +28,17 @@ class RavenActivity : AppCompatActivity() {
...
+
+    val model: RavenModel by viewModels()
+    setContentView(
+      WorkflowLayout(this).apply { start(model.renderings, viewRegistry) }
     )
+
+    lifecycleScope.launch {
+      model.running.collect { running ->
+        if (!running) finish()
+      }
```
Comment (zach-klippenstein) [inline samples/containers/app-raven/src/main/java/com/squareup/sample/ravenapp/RavenActivity.kt:40]:
```suggestion
      model.running.first { !it }
      finish()
```
Wdyt?

File: samples/containers/app-raven/src/main/java/com/squareup/sample/ravenapp/RavenActivity.kt [hunk 11]
```diff
@@ -41,3 +47,20 @@ class RavenActivity : AppCompatActivity() {
     }
   }
 }
+
+class RavenModel(savedState: SavedStateHandle) : ViewModel() {
+  private val _running = MutableStateFlow(true)
+  val running: StateFlow<Boolean> = _running
```
Comment (zach-klippenstein) [inline samples/containers/app-raven/src/main/java/com/squareup/sample/ravenapp/RavenActivity.kt:53]: This could just be a `CompletableJob`/`Job` which expresses the contract a little more accurately I think. 

Then the previous code would be 
```
running.join()
finish ()
```

File: samples/todo-android/app/src/main/java/com/squareup/sample/mainactivity/ToDoActivity.kt [hunk 12]
```diff
@@ -0,0 +1,68 @@
...
+      )
+  }
+}
+
+class ToDoModel(private val savedState: SavedStateHandle) : ViewModel() {
+  private lateinit var renderings: StateFlow<Any>
+
+  @OptIn(WorkflowUiExperimentalApi::class)
+  fun ensureWorkflow(externalFilesDir: File): StateFlow<Any> {
+    if (!::renderings.isInitialized) {
```
Comment (zach-klippenstein) [inline samples/todo-android/app/src/main/java/com/squareup/sample/mainactivity/ToDoActivity.kt:52]: I think `isInitialized` is almost always a code smell. Just make the property nullable.

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/AndroidRenderWorkflow.kt [hunk 13]
```diff
@@ -0,0 +1,266 @@
...
+/**
+ * An Android `ViewModel`-friendly wrapper for [com.squareup.workflow1.renderWorkflowIn],
+ * for use with a [workflow] that takes no input (that is, has `PropsT` set to [Unit]).
+ *
+ *    @OptIn(WorkflowUiExperimentalApi::class)
+ *    class HelloWorkflowActivity : AppCompatActivity() {
+ *      override fun onCreate(savedInstanceState: Bundle?) {
+ *        super.onCreate(savedInstanceState)
+ *
+ *        val model: HelloViewModel by viewModels()
```
Comment (zach-klippenstein) [inline workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/AndroidRenderWorkflow.kt:26]: Did you mean to put this in the method instead at the class level?

**Review by zach-klippenstein — APPROVED** [review]

File: workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/AndroidRenderWorkflow.kt (hunk 13 above)
Comment (rjrjr) [reply workflow-ui/core-android/src/main/java/com/squareup/workflow1/ui/AndroidRenderWorkflow.kt:26]: Pretty sure it won't work there.

**Comment by rjrjr** [comment]
Gonna get rid of the ViewRegistry uses in the tutorial while I'm here.

**Comment by rjrjr** [comment]
Oh, looks like it's more practical to update the tutorials after we push the next release. Will follow up.

File: samples/containers/app-raven/src/main/java/com/squareup/sample/ravenapp/RavenActivity.kt (hunk 11 above)
Comment (rjrjr) [reply samples/containers/app-raven/src/main/java/com/squareup/sample/ravenapp/RavenActivity.kt:53]: I like it, though if feels a little funny to expose an object that leaks its `complete()` method like that. Doing it anyway.

Comment (rjrjr) [reply samples/containers/app-raven/src/main/java/com/squareup/sample/ravenapp/RavenActivity.kt:53]: What if we gave the model its own `suspend fun` for this? 

```kotlin
suspend fun waitForExit()
```

Comment (rjrjr) [reply samples/containers/app-raven/src/main/java/com/squareup/sample/ravenapp/RavenActivity.kt:53]: From another sample. This has to be two separate `launch` calls, right? Otherwise the `collect` will never terminate and we'll never finish.

```kotlin
    lifecycleScope.launch {
      model.renderings.collect { Timber.d("rendering: %s", it) }
    }
    lifecycleScope.launch {
      model.waitForExit()
      finish()
    }
```

**Comment by rjrjr** [comment]
@steve-the-edwards It won't let me merge unti you approve, b/c of the requested changes.

**Comment by rjrjr** [comment]
Got my green, got my LG from Zach, I'm going to merge this thing.

@zach-klippenstein whenever you get a chance to roll a new release with this, that would be appreciated.
