### PR TITLE
Makes snapshots lazy again.

### LINKED ISSUE #223: Snapshot laziness is broken by RenderingSnapshot.equals
I suspect that this call in `renderWorkflowIn` has broken it:

```kotlin
      // After receiving an output, the next render pass must be done before emitting that output,
      // so that the workflow states appear consistent to observers of the outputs and renderings.
      renderingsAndSnapshots.value = runner.nextRendering()
```
b/c of a call to `equals` in `StateFlowImpl`

Screen Shot 2020-10-27 at 10 23 56 AM

Should be a simple fix, make `RenderingAndSnapshot.equals` and `hashCode` ignore the `Snapshot`.

https://workflow-community.slack.com/archives/CHTFPR277/p1603819369039000

### PR DESCRIPTION
**Pull request by rjrjr**
`renderWorkflowIn` uses a `MutableStateFlow` as the source of its
`RenderingAndSnapshot` stream, and that class does an equality check as an
optimization.

Fix is to change `RenderingAndSnapshot` to ignore its `Snapshot` in `equal`,
`hashCode`, and while we're at it `toString`. Danger here is that we'll drop
updates that change only the `Snapshot`, but that seems like a pretty weird
case anyway.

Alternative would be to make `RenderingAndSnapshot` always fail equality, but
that seems like it'd be an even bigger landmine.

closes #223

### CODE REVIEW

**Comment by zach-klippenstein** [comment]
> Danger here is that we'll drop updates that change only the Snapshot

Snapshots should be a pure function of state, and renderings are always re-created at the same time as snapshots, whenever state changes. So I think this is impossible for well-behaved workflows, and definitely something we should explicitly not support if it ever actually comes up (which i've never seen it do).

**Comment by zach-klippenstein** [comment]
in general, with these sorts of changes, I'm worried about the implications of violating the assumption that data classes are equatable. However, this particular class is only used for multiple return values, and I'm pretty sure it's nearly always immediately split into components, so I don't expect it will actually throw anything off.

**Review by steve-the-edwards — APPROVED** [review]

File: workflow-runtime/src/main/java/com/squareup/workflow1/RenderingAndSnapshot.kt [hunk 1]
```diff
@@ -21,4 +21,21 @@ package com.squareup.workflow1
 data class RenderingAndSnapshot<out RenderingT>(
   val rendering: RenderingT,
   val snapshot: TreeSnapshot
-)
+) {
+
+  override fun equals(other: Any?): Boolean {
+    return when {
+      this === other -> true
+      javaClass != other?.javaClass -> false
```
Comment (zach-klippenstein) [inline workflow-runtime/src/main/java/com/squareup/workflow1/RenderingAndSnapshot.kt:29]: `other !is RenderingAndSnapshot ->` reads better and is more idiomatic, imo.

File: workflow-runtime/src/main/java/com/squareup/workflow1/RenderingAndSnapshot.kt [hunk 2]
```diff
@@ -21,4 +21,21 @@ package com.squareup.workflow1
...
+      else -> rendering == (other as RenderingAndSnapshot<*>).rendering
```
Comment (zach-klippenstein) [inline workflow-runtime/src/main/java/com/squareup/workflow1/RenderingAndSnapshot.kt:30]: We could still do an identity comparison for `snapshot`, but then we'd need to use `System.identityHashCode` for the hashCode implementation and I don't believe there's any multiplatform version of that function (although there is a [native one](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.native/identity-hash-code.html), apparently). Anyway, probably more work than it's worth.

Although I'm kind of thinking it would be better to just make this a simple identity comparison and not include even the rendering, since it seems overly complicated, and not useful, to have only partial equality.

File: workflow-runtime/src/test/java/com/squareup/workflow1/RenderWorkflowInTest.kt [hunk 3]
```diff
@@ -151,6 +153,35 @@ class RenderWorkflowInTest {
...
+  // https://github.com/square/workflow-kotlin/issues/223
+  @Test fun `snapshots are lazy`() {
+    lateinit var sink: Sink<String>
+    var snapped = false
+
+    val workflow = Workflow.stateful<Unit, String, Nothing, String>(
+        initialState = { _, _ -> "unchanging state" },
+        snapshot = { Snapshot.of {
+          // We need to use snapped b/c the fail call is swallowed.
+          // https://github.com/square/workflow-kotlin/issues/223
```
Comment (zach-klippenstein) [inline workflow-runtime/src/test/java/com/squareup/workflow1/RenderWorkflowInTest.kt:165]: Nit: I think you linked the wrong issue here, did you mean #224?

**Comment by rjrjr** [comment]
> in general, with these sorts of changes, I'm worried about the implications of violating the assumption that data classes are equatable. However, this particular class is only used for multiple return values, and I'm pretty sure it's nearly always immediately split into components, so I don't expect it will actually throw anything off.

At the very least I should punch add kdoc making this behavior explicit.

File: workflow-runtime/src/test/java/com/squareup/workflow1/RenderWorkflowInTest.kt [hunk 4]
```diff
@@ -151,6 +153,35 @@ class RenderWorkflowInTest {
...
+    )
+    val props = MutableStateFlow(Unit)
+    val renderings = renderWorkflowIn(workflow, scope, props) {}
+
+    renderings.value.rendering.let { rendered ->
+      assertEquals("unchanging state", rendered)
+      sink.send("unchanging state")
+    }
+
+    assertFalse(snapped)
```
Comment (zach-klippenstein) [inline workflow-runtime/src/test/java/com/squareup/workflow1/RenderWorkflowInTest.kt:182]: I'd probably add one more check here to make sure the next snapshot is not equal, and that the first snapshot is still not snapped.

File: workflow-runtime/src/main/java/com/squareup/workflow1/RenderingAndSnapshot.kt [hunk 5]
```diff
@@ -21,4 +21,21 @@ package com.squareup.workflow1
 data class RenderingAndSnapshot<out RenderingT>(
   val rendering: RenderingT,
   val snapshot: TreeSnapshot
-)
+) {
+
+  override fun equals(other: Any?): Boolean {
```
Comment (zach-klippenstein) [inline workflow-runtime/src/main/java/com/squareup/workflow1/RenderingAndSnapshot.kt:26]: We should write a small test for this equals/hashcode too, now that it's explicit.

**Review by zach-klippenstein — CHANGES_REQUESTED** [review]

File: workflow-runtime/src/test/java/com/squareup/workflow1/RenderWorkflowInTest.kt (hunk 3 above)
Comment (rjrjr) [reply workflow-runtime/src/test/java/com/squareup/workflow1/RenderWorkflowInTest.kt:165]: Yup, thanks.

File: workflow-runtime/src/main/java/com/squareup/workflow1/RenderingAndSnapshot.kt (hunk 2 above)
Comment (rjrjr) [reply workflow-runtime/src/main/java/com/squareup/workflow1/RenderingAndSnapshot.kt:30]: > Although I'm kind of thinking it would be better to just make this a simple identity comparison and not include even the rendering, since it seems overly complicated, and not useful, to have only partial equality.

Yeah, I like that better, seems less magical. And that could be as simple as dropping `data` from the class declaration.

**Review by zach-klippenstein — APPROVED** [review]
