### PR TITLE
Fix expectWorker to match on concrete types of generic workers.

### LINKED ISSUE #153: RenderTester.expectWorker doesn't match workers that are instances of generic worker types
E.g. `TypedWorker<T>`, which is the type of the workers returned by most `asWorker()` functions. If your workflow does `runningWorker(flowOf("hello").asWorker()) { … }`, and your test does `expectWorker(typeOf<Worker<String>>())`, it will not match, because `Worker<String>` is not a supertype of `TypedWorker<Any?>`, which is the erased type of the actual worker at runtime.

### PR DESCRIPTION
**Pull request by zach-klippenstein**
Fixes #153.

### CODE REVIEW

File: workflow-core/src/main/java/com/squareup/workflow1/RenderContext.kt [hunk 1]
```diff
@@ -173,10 +172,13 @@ fun <PropsT, StateT, OutputT, ChildRenderingT>
  *
  * @param key An optional string key that is used to distinguish between identical [Worker]s.
  */
-fun <PropsT, StateT, OutputT> BaseRenderContext<PropsT, StateT, OutputT>.runningWorker(
-  worker: Worker<Nothing>,
+/* ktlint-disable parameter-list-wrapping */
+inline fun <reified W : Worker<Nothing>, PropsT, StateT, OutputT>
+    BaseRenderContext<PropsT, StateT, OutputT>.runningWorker(
+  worker: W,
```
Comment (zach-klippenstein) [inline workflow-core/src/main/java/com/squareup/workflow1/RenderContext.kt:178]: Without this, matching a `Worker<Nothing>` will fail because the type captured here will be `Worker<java.lang.Void>`, which is not a subtype of `Worker<Nothing>`.

File: workflow-testing/src/test/java/com/squareup/workflow1/testing/WorkerRenderExpectationsTest.kt [hunk 2]
```diff
@@ -385,4 +387,15 @@ class WorkerRenderExpectationsTest {
           )
         }
   }
+
+  @Test fun `expectWorker on TypedWorker`() {
```
Comment (zach-klippenstein) [inline workflow-testing/src/test/java/com/squareup/workflow1/testing/WorkerRenderExpectationsTest.kt:391]: Verified manually that this test fails without the change.
