### PR TITLE
Fix RenderTester workflow class matching for mocked workflow instances.

### LINKED ISSUE #155: RenderTester expectWorkflow doesn't match workflows created with Mockito
Turns out that the KClasses of objects mockito returns for a given interface aren't considered subclasses of the KClass of that interface by kotlin reflection, which means that the logic to match a mock workflow to the expectation of its supertype fails.

### PR DESCRIPTION
**Pull request by zach-klippenstein**
Turns out that mocks made with at least some mocking libraries (tested
with Mockito and Mockk) aren't seen by Kotlin reflection as subclassing
their mocked types. That is, `Interface::class.isSuperclassOf(mock<Interface>()::class)`
returns false. This change works around that issue by falling back to java reflection
if `KClass.isSuperclassOf` returns false.

Fixes #155.

### CODE REVIEW

File: workflow-testing/src/test/java/com/squareup/workflow1/testing/RealRenderTesterTest.kt [hunk 1]
```diff
@@ -1201,4 +1234,10 @@ class RealRenderTesterTest {
 
   @Suppress("unused")
   private interface ContravariantGenericType<in T>
+
+  // For mocking tests. Interfaces can't be defined inside functions, and Mockito can't handle
+  // the class names of local classes defined in functions named like these test functioøns are.
```
Comment (steve-the-edwards) [inline workflow-testing/src/test/java/com/squareup/workflow1/testing/RealRenderTesterTest.kt:1239]: is this l33t speak for function??

Comment (zach-klippenstein) [reply workflow-testing/src/test/java/com/squareup/workflow1/testing/RealRenderTesterTest.kt:1239]: 🤦

Comment (zach-klippenstein) [inline workflow-testing/src/test/java/com/squareup/workflow1/testing/RealRenderTesterTest.kt:1239]:
```suggestion
  // the class names of local classes defined in functions named like these test functions are.
```

File: workflow-testing/src/main/java/com/squareup/workflow1/testing/RealRenderTester.kt [hunk 2]
```diff
@@ -344,3 +344,14 @@ internal fun WorkflowIdentifier.realTypeMatchesExpectation(
...
+
+/**
+ * Falls back to using Java reflection to determine subclass relationship.
+ *
+ * Kotlin's [isSuperclassOf] doesn't play nice with Mockito or Mockk:
+ * `Interface::class.isSuperclassOf(mock<Interface>()::class)` will return false.
+ *
+ * See https://github.com/square/workflow-kotlin/issues/155.
+ */
+private fun KClass<*>.isJavaMockOf(type: KClass<*>): Boolean =
```
Comment (rjrjr) [inline workflow-testing/src/main/java/com/squareup/workflow1/testing/RealRenderTester.kt:356]: Any reason not to just use `isAssignableFrom` and drop `isSuperclassOf` entirely?

Comment (zach-klippenstein) [reply workflow-testing/src/main/java/com/squareup/workflow1/testing/RealRenderTester.kt:356]: Just keeping the intent clear and highlighting that this is an issue with java mocking libraries. I don't feel too strongly about keeping both checks.

Comment (zach-klippenstein) [reply workflow-testing/src/main/java/com/squareup/workflow1/testing/RealRenderTester.kt:357]: I added a link to the Kotlin reflection bug this is working around, would you be ok keeping both now?

**Comment by zach-klippenstein** [comment]
Github seems to be having issues, I ran `./gradlew clean build connectedCheck` locally and everything passed, so I'm just going to merge without waiting.
